name: Setup Ubuntu Environment and Run Tmate

on: [push, workflow_dispatch]

jobs:
  setup-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update and upgrade system packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt-get update && sudo apt-get upgrade -y

      - name: Install required packages
        run: |
          sudo apt-get install -y python3 python3-pip nodejs npm tmate openssh-client neofetch git curl procps ca-certificates
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install Python Telegram bot library
        run: pip3 install --no-cache-dir pytelegrambotapi

      - name: Generate fresh SSH key for tmate
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -N '' -q
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa

      - name: Create dummy file to keep session alive
        run: |
          mkdir -p ~/app
          echo "Tmate Session Running..." > ~/app/index.html
          cd ~/app

      - name: Start HTTP server and tmate session
        run: |
          python3 -m http.server 6080 &
          tmate -F
